
GET http://localhost:3000/api/user/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdoYW5hQGdoYW5hLmNvbSIsIm5hbWUiOiJqamQxIiwiaWF0IjoxNjM2MTc2MjcxLCJleHAiOjE2MzYxNzYyODF9.b4kjHN_D_BHueMj5LW0kYQv9qtxd7J7LD7CT16sCsyk
###

POST http://localhost:3000/api/auth/signUp
Content-Type: application/json

{
  "name": "jjd1",
    "email": "ghana369@gmail.com",
  "password": "password1"
}

###
POST  http://localhost:3000/api/auth/signIn
Content-Type: application/json

{
  "email": "ghana369@gmail.com",
  "password": "password1"
}
###
delete  http://localhost:3000/api/auth/signOut
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdoYW5hQDEyMzQuY29tIiwibmFtZSI6ImpqZDEiLCJpYXQiOjE2MzYyMDM4NjUsImV4cCI6MTYzNjgwODY2NX0.cfUR4mXMb_KXvMJhyAyVXLR1NvbBjh9k2sTeHOohI7Y"
}

###
POST http://localhost:3000/api/auth/refreshToken
Content-Type: application/json

{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdoYW5hQDEyMzQuY29tIiwibmFtZSI6ImpqZDEiLCJpYXQiOjE2MzYyMDM4NjUsImV4cCI6MTYzNjgwODY2NX0.cfUR4mXMb_KXvMJhyAyVXLR1NvbBjh9k2sTeHOohI7Y"
}

###
GET http://localhost:3000/api/board/boards

###
GET http://localhost:3000/api/board/boards/6183f2ce4283e9acd1a57553

###
POST http://localhost:3000/api/board/write
Content-Type: application/json

{
  "name": "test",
  "title": "test title",
  "content": "test content"
}